image: golang:latest

stages:
  - test
  - build

variables:
  GO_ROOT_DIR: site/
  BIN_DIR: bin/

test:
  stage: test
  script:
    - cd $GO_ROOT_DIR
    #- go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  stage: build
  script:
    - cd $GO_ROOT_DIR
    - mkdir -p $BIN_DIR
    - go build -o $BIN_DIR cmd/rapidart/main.go
  #artifacts:
    #paths:
      #- ${GO_ROOT_DIR}/$BIN_DIR
