image: golang:latest

stages:
  - test
  - build

variables:
  GO_ROOT_DIR: site/
  BIN_DIR: bin/

format:
  stage: test
  script:
    - cd $GO_ROOT_DIR
    #- go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ${GO_ROOT_DIR}/... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p $BIN_DIR
    - cd $GO_ROOT_DIR
    - go build -o $BIN_DIR cmd/rapidart/main.go
  artifacts:
    paths:
      - $BIN_DIR
