image: golang:latest

stages:
  - test
  - build

variables:
  GO_ROOT_DIR: site/
  BIN_DIR: bin/

format:
  stage: test
  script:
    - go fmt $(go list ${GO_ROOT_DIR}/... | grep -v /vendor/)
    - go vet $(go list ${GO_ROOT_DIR}/... | grep -v /vendor/)
    - go test -race $(go list ${GO_ROOT_DIR}/... | grep -v /vendor/)

compile:
  stage: build
  script:
    - mkdir -p $BIN_DIR
    - go build -o $BIN_DIR ${GO_ROOT_DIR}/...
  artifacts:
    paths:
      - $BIN_DIR
