version: '3.8'

services:
  my-mariadb:
    image: mariadb:latest
    container_name: my-mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=test123
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "0.0.0.0:3306:3306"

  my-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin
    restart: always
    links:
      - "my-mariadb:db"
    ports:
      - "8080:80"

volumes:
  mariadb_data: