from locust import HttpUser, TaskSet, task, between

# This entire stress/load test was generated by ChatGPT
class UserBehavior(TaskSet):
    @task
    def perform_request(self):
        # Define a GET request for the application.
        self.client.get("/")

class WebsiteUser(HttpUser):
    tasks = [UserBehavior]
    wait_time = between(1, 3)  # Users wait 1-3 seconds between requests
